### ISSUE TITLE
Add voucher execution

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#101]
## 📄 Context

Be able to execute a voucher generated by a Rollups Application.

## ✔️ Solution

When a connection exists and a voucher is available in the `input details` area, Display a button to execute the voucher **if it has not been executed yet**. The arguments for execution can be found in the `Voucher` type returned by the rollup graphQL. 

<details>
<summary>GraphQL references</summary>

HoneyPot graphQL playground: https://honeypot.sepolia.rollups.staging.cartesi.io/graphql

```graphql
type Voucher {
  index: Int!
  input: Input!
  destination: String!
  payload: String!
  proof: Proof
}
```
</details>

<details>
<summary>CartesiDApp contract references</summary>
<br>
Methods:

* [wasVoucherExecuted](https://github.com/cartesi/rollups-contracts/blob/77ff2c08928b871348b6e2bf3b6f5d7f3c95c9dc/onchain/rollups/contracts/dapp/CartesiDApp.sol#L148)
* [executeVoucher](https://github.com/cartesi/rollups-contracts/blob/77ff2c08928b871348b6e2bf3b6f5d7f3c95c9dc/onchain/rollups/contracts/dapp/CartesiDApp.sol#L103C14-L103C28)
</details>

Wagmi reference: [Wagmi-cli docs](https://wagmi.sh/cli/getting-started)

## 📈 Subtasks

- [x] Update rollups-wagmi package to include CartesiDApp ABI for code generation. 
- [x] In the input details area, only the voucher area should present the button for action.
- [x] A spinner should be displayed for feedback While checking if the voucher was executed.
- [x] When the voucher was executed, the button should be disabled, and the copy displayed is `Executed`.
- [x] Use [useWaitForTransaction](https://1.x.wagmi.sh/react/hooks/useWaitForTransaction) for the transaction loading.
- [x] Display a `Execute` button when the voucher is not executed.
- [x] Add stories to cover the new UI and states (checking / while executing) 
- [x] Add test cases.

## 🎯 Definition of Done

- [x] Be able to execute an Application voucher.

**Comment by brunomenezes** [comment]
@tuler, adding you for review as we discussed.
