### ISSUE TITLE
Add Search UI

### ISSUE THREAD

**Issue by dandheedge** [cartesi/rollups-explorer#111]
## 📄 Context

With the increasing number of data, users often find it challenging to quickly locate specific data for input or application.

## ✔️ Solution

Develop a search UI component that allows users to efficiently filter and find the data they are looking for. The search component would be on two pages.

## 📈 Subtasks

- [ ] Implement a search bar that enables users to effectively filter and find specific data on `Applications` page. 
- [ ] Implement a search bar that enables users to effectively filter and find specific data on `Inputs` page. 

## 🎯 Definition of Done

- [ ]  A fully operational search bar that accurately filters and displays the specific data based on user input.

### Example 

<img width="936" alt="Screenshot 2024-01-30 at 13 17 06" src="https://github.com/cartesi/rollups-explorer/assets/13269955/10dea24c-7dbc-4065-a10f-eba718d6108e">
