### ISSUE TITLE
ERC-1155 Deposit 

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#113]
## 📄 Context

Applications accept deposits of ERC-1155 tokens by interacting with the [ERC1155SinglePortal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC1155SinglePortal/) or [ERC1155BatchPortal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC1155BatchPortal/) smart contracts.

Before the transfer, the caller should enable approval to manage all of theirs tokens by calling the `setApprovalAll` in the token's contract.

## ✔️ Solution

ERC-1155: Multi Token Standard (https://eips.ethereum.org/EIPS/eip-1155)

Documentation about the ERC-1155 (Single) deposit:
https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC1155SinglePortal/

Documentation about the ERC-1155 (Batch) deposit:
https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC1155BatchPortal/
**PS: For Batch, make sure the `_tokenIds` and `_values` have the same length.**

The input for ERC-1155 contract address should use an autocomplete by fetching the Token list from the backend.
The input for the application contract address should use an auto-complete by fetching the Application list from the backend. i.e. same behaviour as e.g. ERC-20 deposit form. 

## 📈 Subtasks

- [x] Create the form for the single deposit.
- [x] Create the form for the batch deposit.
- [x] Implement the `setApprovalAll` transaction.
- [x] Handle Transaction Errors.
- [x] Implement the `depositSingleERC1155Token` transaction.
- [x] Implement the `depositBatchERC1155Token` transaction.
- [x] Ensure that base and exec layer hex data is correctly encoded (no double encoding)
- [x] Add test cases.

## 🎯 Definition of Done

- [x] A deposit using the `ERC1155SinglePortal` complete with success.
- [x] A deposit using the `ERC1155BatchPortal` complete with success.
