### ISSUE TITLE
Implement Application Overview Card and Table

### ISSUE THREAD

**Issue by dandheedge** [cartesi/rollups-explorer#116]
## 📄 Context

Applications page is not displaying the total number of applications nor does it provide a table listing the applications owned by the user.

## ✔️ Solution

1. Create a summary card in the `/home` page that shows total applications owned by user.
2. Create a table component in the `/applications` that shows all applications owned by user.

**Inspiration**

<img width="1255" alt="Screenshot 2024-02-13 at 13 54 29" src="https://github.com/cartesi/rollups-explorer/assets/13269955/21547519-d4fd-4b46-b3fc-96ba30e8a5a3">

## 📈 Subtasks

- [x] Create a card that shows total user's applications on the homepage
- [x] Create a table that shows only applications owned by user
- [x] Add test cases for all added logic and UI
- [x] Add stories for the UI under the `workshop` project

## 🎯 Definition of Done

- [x] A card component titled My Component accurately displays the total number of applications the user has.
- [x] Table component that only display the user's Applications
- [x] Correctly use the query on each component
- [x] Existing and new unit tests pass successfully

**Comment by nevendyulgerov** [comment]
Hey @dandheedge , @brunomenezes , maybe we should display a simplified the card with user-owned applications on the home page as well? Right now, we have there two cards for latest inputs and latest applications.

**Comment by brunomenezes** [comment]
> ~Hey @dandheedge , @brunomenezes , maybe we should display a simplified card with user-owned applications on the home page as well? Right now, we have there two cards for latest inputs and latest applications.~
> 
> I noticed in the [PR](https://github.com/cartesi/rollups-explorer/pull/125) for this that the above suggestion is already implemented.

Exactly, that was the feature discussed: the card that has the info to be displayed on the Home page and the table for the applications page (I think the issue `context` section needs some updating). @dandheedge, maybe refining the issue a bit more, including where these "new components" will be added, would make things clearer for a person without context or the reviewer of this PR once it is ready.

Also, in the DoD;
I wording update is necessary for the first checkbox. "A card component titled **My Component** accurately displays the total number of applications the user has."
