### ISSUE TITLE
Add more unit tests for transaction forms

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#127]
## 📄 Context

Let's cover all existing transaction forms like `Ether` deposit, `ERC20` deposit, `ERC721` deposit and `Raw` input forms with as many unit tests as possible. The goal is to increase stability and safety when using those forms from the app because they make transactions and on prod it's crucial that everything works as expected for them.

## 📈 Subtasks

- [x] Add more unit tests for `Ether` deposit form
- [ ] Add more unit tests for `ERC20` deposit form
- [ ] Add more unit tests for `ERC721` deposit form
- [x] Add more unit tests for `Raw` input form
- [ ] Make sure that all forms have tests preventing issues like double hex encoding of base and exec layer data

## 🎯 Definition of Done

- [ ] All existing and new tests pass successfully.
