### ISSUE TITLE
Move VoucherExecution component under packages/ui

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#129]
## 📄 Context

As per this [comment](https://github.com/cartesi/rollups-explorer/pull/115#pullrequestreview-1921502734) move the `VoucherExecution` component under `packages/ui`.

## 📈 Subtasks

- [ ] `VoucherExecution` is moved to `packages/ui`
- [ ] Test suite for `VoucherExecution` is moved to `packages/ui`

## 🎯 Definition of Done

- [ ] Executing a voucher works ok
- [ ] Tests for voucher execution are passing

**Comment by brunomenezes** [comment]
Hi @nevendyulgerov, my comment was to discuss the motivation behind the current choice rather than move it directly. 
For example, a few questions on that end;

* What was the motivation to add to the `apps/web` instead of the `packages/ui`? 
* Is that because of the types generated by our codegen tools?  (Generators are good if you accept that sometimes some work will be needed on rough edges). 
* Is that related to extensibility?

**Comment by nevendyulgerov** [comment]
I think we can close this one for the time being.
