### ISSUE TITLE
Bump Mantine packages to latest version [7.7.0]

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#132]
## 📄 Context
We use [mantine.dev](https://mantine.dev) as the UI framework for CartesiScan. We are currently using v7.5; a new v7.7 was released a week ago. So we bump the version and move together.

Mantine: [Release notes](https://github.com/mantinedev/mantine/releases/tag/7.7.0)
What's new (v 7.6): [Discord release channel](https://discord.com/channels/854810300876062770/915166464061890602/1211625146914181130)

All Mantine packages should be bumped to the latest version i.e. v7.7.0. 

**PS: Check on any API changes after upgrading. That would not be the first time a typescript problem arose from it.**

## 📈 Subtasks

- [ ] Upgrade Mantine packages on `packages/ui`
- [ ] Upgrade Mantine packages on `apps/web`
- [ ] Upgrade Mantine packages on `apps/workshop`
- [ ] Make sure dependencies are updated in the lock file (yarn.lock).
- [ ] Verify web app is working on big and small screens. i.e. a full check on UI functionalities (clicks / modals, all works as expected)
- [ ] Verify web app is working correctly inside [app.safe.global](https://app.safe.global/)
- [ ] Verify that the workshop app is working not just locally but also in the deployed version.
- [ ] Github CI is passing.
