### ISSUE TITLE
Tweak connections scroll area so that the entire viewport height is used

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#137]
## 📄 Context

Currently, if you add more than 4 connections, the scroll area inside the connections sidebar hides the rest. Here's a video demonstrating this:

https://github.com/cartesi/rollups-explorer/assets/6005179/92253e1f-9443-4955-865f-631eeeafdc97

This is because for the scroll area we are setting the height to be half of the viewport. I think we can improve this and use the entire viewport so more connections can be visible without the need to scroll down. Here's a video demonstrating this:

https://github.com/cartesi/rollups-explorer/assets/6005179/312b4d80-0515-4e28-bb19-eaca95e22afd

## ✔️ Solution

To achieve this, we can leverage [ScrollArea.Autosize](https://mantine.dev/core/scroll-area/#scrollareaautosize) with the following config:

```
<ScrollArea.Autosize mah={viewportHeight - 120} type="never">
  ...
</ScrollArea.Autosize>
```

In the above code, we are setting the max height to be the viewport minus space for one card (~90px) + its margins (~30px). This is so that the last card is not hidden (using the full viewport height results in that).

## 📈 Subtasks

- [ ] In `ConnectionView` component utilize `ScrollArea.Autosize` to use the entire viewport height
- [ ] Set the `mah` prop of `ScrollArea.Autosize` to a value that will utilize as much vertical space as possible without hiding any connection cards.

## 🎯 Definition of Done

- [ ] The scroll area for the connections list is using the entire viewport height, allowing for more connections to be visible without scrolling.

**Comment by nevendyulgerov** [comment]
Hey @brunomenezes , @dandheedge , please share your thoughts on this one. Although users won't probably add that many connections (4+), I think this small tweak makes sense and will slightly improve the UX.

**Comment by brunomenezes** [comment]
> Hey @brunomenezes , @dandheedge , please share your thoughts on this one. Although users won't probably add that many connections (4+), I think this small tweak makes sense and will slightly improve the UX.

The idea of it to use half the viewport is to make room for ABIs, that would come to share space in that drawer.
