### ISSUE TITLE
Upgrade storybook to v8

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#144]
## 📄 Context

Storybook recently released version 8. Let's upgrade to it using the following [migration guide](https://storybook.js.org/docs/migration-guide). This is for the `apps/workshop` project.

## 📈 Subtasks

- [x] Upgrade core storybook packages to v8.
- [x] Upgrade storybook plugins and remove deprecated ones.
- [x] Make sure dependencies are updated in the lock file (package-lock.json).
- [x] Verify whether everything is working as expected.
