### ISSUE TITLE
Upgrade @cartesi/rollups to latest version

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#149]
## 📄 Context

Currently, the `rollups-wagmi` package uses the `cartesi/rollups` dependency. We need to upgrade the `yarn.lock` to bump from the current `v1.1.0` to the latest currently `v1.2.0`.  That is to keep updated with the latest releases. 

## 📈 Subtasks

- [x] Make sure dependencies are updated in the lock file (package-lock.json).
- [x] Verify if wagmi code generation is working as expected
- [x] Check if `send transaction` operations continue to behave as expected.
