### ISSUE TITLE
Add connections page

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#150]
## 📄 Context
Today, the connections list lives inside an `<aside>` visible when clicking the vertical dots icon in the header. The intention is to allow the connection to have its page.

## ✔️ Solution
Move the connection to its page and remove the `<aside />` and all mechanisms necessary for it to work.

* Remove the vertical dots (a.k.a vertical kebab icon) and also the whole aside area. 
* Create a collapsable Settings with a connection link to the new page (**Settings Icon [TbAdjustmentsHorizontal](https://react-icons.github.io/react-icons/search/#q=TbAdjustmentsHorizontal)**). 
* Settings is a virtual grouping, i.e. no /settings route (For now). 
* Implement a connections page (/connections).
* List the connection cards.

## 📈 Subtasks

- [x] Remove `<aside />` and the mechanism to make it work.
- [x] Add Settings group with connection as sub-item.
- [x] Add new connection page under `/connections` route.
- [x] Remove collapse and scroll area from `ConnectionView` component
- [x] Remove obsolete tests for `ConnectionView` component
- [x] Add tests for Settings group

## 🎯 Definition of Done

- [x] The previous view is removed, including all triggers to it. i.e. `<aside>`
- [x] Can list all the created connections under `/connections`.
- [x] Can create a connection from `/connections`.
- [x] All tests are passing.
