### ISSUE TITLE
Add new route for application's input

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#152]
## 📄 Context
We will add more ways to access different types of output from the application's backend. Therefore, the content in the application's `Home` should be moved to a matching route i.e. `/applications/<address>/inputs`. That will give space and granularity to explore other views on specific outputs when available e.g. notices/vouchers/reports. 

_PS: That will serve as a reference for the output unification that will come with rollups V2._

## ✔️ Solution
Move the content in the `/applications/<address>` to the matching route.

* Move the current application's `Home`  content to `/applications/<address>/inputs`
* Update the input's table link for the `application` address to the new URL.
* Update the `Home` page cards application link to point to the new URL.
* Update the `Inputs` action button in the applications table to the new URL i.e. located in `/applications`

## 📈 Subtasks

- [x] Move application inputs content to the new URL
- [x] Update the Home page cards links to the new URL format for Application addresses.
- [x] Update application links format in the `Inputs` page. 
- [x] Update application links format in the `Home` page.
- [x] Update tests (if required)
- [x] Update stories (if required)

## 🎯 Definition of Done

- [x] The application input list is under `/applications/<address>/inputs`
- [x] Clicking the application address in the inputs table goes to the specific application input list. 
- [x] Clicking the application address in any of the `Home` page summary cards goes to the application's input list.
- [x] Clicking the the inputs action button in the list of applications goes to the correct application input list page.
- [ ] CI is passing all the checks
- [ ] Vercel build is passing.
