### ISSUE TITLE
Add Application summary under `/applications/<address>`

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#153]
## 📄 Context
The home of the application should display a brief summary of its state. Total numbers for inputs will always be available, adding numbers for notices/vouchers/reports when a connection is available to check these numbers and a brief list of the latest inputs including short information.

Depends on:
* #152 

PS: #152 needs to go first, so we "clean" the area to the next "friend".

## ✔️ Solution
Implement a summary page for the application under route `/applications/<address>`

* Display summary cards with total Inputs / Vouchers / Notices / Reports 
* If a connection is not available, a Skeleton resembling the 3 cards that require connection should be displayed instead with a call to action saying `ADD CONNECTION`
* A summary card below the four cards / Skeleton should list the latest 6 inputs (Similar to Home page)
    * Display the following read-only tabular information [ From / Method / Age ]
    * Bottom include a `VIEW INPUTS` button/link (go to `/applications/<address>/inputs`)

### A few icons to use (Selection inspired by a work done by Celine Lee in the past):
Report: [TbReportAnalytics](https://react-icons.github.io/react-icons/search/#q=TbReportAnalytics)
Notices: [TbAlertTriangle](https://react-icons.github.io/react-icons/search/#q=TbAlertTriangle)
Vouchers: [TbTicket](https://react-icons.github.io/react-icons/search/#q=TbTicket)

## 📈 Subtasks

- [x] Add breadcrumb `home / applications / <address>` (possible to copy the address)
- [x] Add the summary cards for Inputs / Notices / Reports / Vouchers
- [x] Add Skeleton and call to action when connection is not available for application (i.e. start connection workflow)
- [x] Add a summary card for the latest 6 inputs.
   - [x] Display tabular information `[ From / Method / Age ]`. PS: Display the usual `No inputs` when no entries are returned.
   - [x] Bottom of the card includes a `VIEW INPUTS` link ( go to `/applications/<address>/inputs`)
- [x] Add test cases.

## 🎯 Definition of Done

- [x] On the application home page, I can see the list of the latest six inputs (including From, method and age)
- [x] On the application home page, I can see the breadcrumb and copy the application address
- [x] On the application home page, I can see the sum of inputs, vouchers, notices and reports.
- [x] On the application home page, when a connection is not available, I can see the skeleton and start the creation of one
- [x] CI checks are passing.
- [x] Vercel build and deploy succeeds.
