### ISSUE TITLE
Add Playwright setup.

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#162]
## 📄 Context
Add the Playwright e2e automation library to the `web` app. Add an initial setup and test case to pave the way. 

## 📈 Subtasks

- [x] Add playwright into `web` project.
- [x] Add an initial test case to start.
- [x] Add any necessary script to integrate with turbo repo.
