### ISSUE TITLE
Add test cases for the Navigation menu.

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#166]
## 📄 Context

Add e2e tests for the navigation menu.

## 📈 Subtasks

- [x] Add test for home page navigation
- [x] Add test for applications page navigation
- [x] Add test for inputs page navigation
- [x] Add test for settings - connection page navigation

## 🎯 Definition of Done

- [x] All new and existing e2e tests are passing
