### ISSUE TITLE
Add test cases for the Home page.

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#168]
## 📄 Context

Add e2e tests for the home page.

## 📈 Subtasks

- [x] Add test for the inputs summary card
- [x] Add test for the applications summary card
- [x] Add test for the latest inputs table
- [x] Add test for the latest applications table

## 🎯 Definition of Done

- [x] All new and existing e2e tests are passing
