### ISSUE TITLE
ERC-20 deposit

### ISSUE THREAD

**Issue by tuler** [cartesi/rollups-explorer#17]
## 📄 Context

DApps accept deposits of ERC-20 tokens by interacting with the [ERC20Portal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC20Portal/) smart contract.

Prior to depositing an allowance must be set to the ERC20Portal contract, which is a standard procedure for ERC-20 transfers.

## ✔️ Solution

Documentation about the ERC-20 deposit:
https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC20Portal/

The input for ERC-20 contract address could use an autocomplete by fetching the Token list from the backend, but this can be left for a future improvement (https://github.com/cartesi/rollups-explorer/issues/18)

The input for the application contract address could use an auto-complete by fetching the Application list from the backend, but this can be left for a future improvement (https://github.com/cartesi/rollups-explorer/issues/19).

## 📈 Subtasks

- [ ] create the form for the deposit
- [ ] implement the approve transaction
- [ ] implement the depositERC20Tokens transaction

## 🎯 Definition of Done

- [ ] transaction successful
