### ISSUE TITLE
Add test cases for the Applications page.

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#170]
## 📄 Context

Add e2e tests for the applications page.

## 📈 Subtasks

- [x] Add test for header
- [x] Add test for All applications table

## 🎯 Definition of Done

- [x] All new and existing e2e tests are passing
