### ISSUE TITLE
Add responsive capability to the applications table

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#171]
## 📄 Context
The table that lists the applications under `/applications` is all stacked up when looking through a small screen device. The idea is to have it responsive in the same way as the table listing inputs. Therefore, when the screen is too small for the content, it should be able to scroll horizontally through the current viewport available with the action column floating.

## ✔️ Solution
Add responsiveness to the applications table. Use the input table as a reference. 

* The cell content does not break the line.
* The action column (last one) floats when it is hidden with a perceived shadow to show that it has content to be scrolled.
* The user can scroll horizontally. 
* When the last column is visible, the shadow should also be gone. 

## 📈 Subtasks

- [ ] Implement the responsive logic in the application's table

## 🎯 Definition of Done

- [ ] The user can horizontally scroll on small screens
- [ ] The user can, without scrolling, click the action buttons through the floating column. 
- [ ] The table works as usual on bigger screens.
