### ISSUE TITLE
Add content filtering by tabs in the applications page

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#172]
## 📄 Context
The application's page (i.e. `/applications`) now lists all applications and the applications belonging to the connected account. Because both have title+pagination-buttons+table, the page became noisy with too much. To return to more driven content, tabs can be added to separate one from the other. 

## ✔️ Solution
Implement two tabs to separate the content listing all the applications from the owned ones. 

* Add two tabs located below the main page title. 
* The tabs should be theme controlled. i.e. Using the default appearance so theme changes affect everywhere accordingly.
* The copy for the tabs .e.g `All Apps` and `My Apps`
* Remove the sub-titles as they become a redundancy, i.e. `My Applications` and `All Applications`
* The default selected tab is the `All Apps`.

## 📈 Subtasks

- [x] Implement the tabs logic. 

## 🎯 Definition of Done

- [x] The user can see the list of all the apps when accessing the applications page. 
- [x] The user can select the tab to see the apps the connected account owns.
- [x] Add unit tests.
