### ISSUE TITLE
Add missing method name for deposits from Portal

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#173]
## 📄 Context
Currently, in the inputs table, deposits coming from the ERC20Portal and EtherPortal display the method's name when the `msgSender` matches the address of such portal contracts.  We are already indexing information for [ERC721Portal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC721Portal/), [ERC1155SinglePortal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC1155SinglePortal/) and [ERC1155BatchPortal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC1155BatchPortal/) but still displaying the `?`

## ✔️ Solution
Implement the method-resolver for each missing portal and display the method name described in the above documentation.

## 📈 Subtasks

- [x] implement the method resolver for ERC721Portal.
- [x] Implement the method resolver for ERC1155SinglePortal.
- [x] Implement the method resolver for ERC1155BatchPortal.
- [x] Add unit tests.

## 🎯 Definition of Done

- [x] The user can see the method name from inputs coming from the ERC721Portal.
- [x] The user can see the method name from inputs coming from the ERC1155SinglePortal.
- [x] The user can see the method name from inputs coming from the ERC1155BatchPortal.
