### ISSUE TITLE
Create responsive table component

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#178]
## 📄 Context

We already have several tables in the app and most of those need to be responsive. As the app evolves, we'll probably add more tables. Currently, the code for responsive tables is spread across their related components. It makes sense that we extract it into a single reusable component so we can:

- quickly bootstrap responsive tables in the app
- create responsive tables on the fly, without the need to remember this implementation detail (as currently is required for standard tables)

## ✔️ Solution

Create a wrapper component `ResponsiveTable` for `mantine`'s `Table` component, so that it is responsive by design. It should work as the responsive table on the inputs page.

## 📈 Subtasks

- [ ] Utilise `ResponsiveTable` in all places where responsive tables are required. 
- [ ] Remove old, duplicate code related to the responsive table behaviour.

## 🎯 Definition of Done

- [ ] All responsive tables are displayed as before but powered by the new `ResponsiveTable` component.
