### ISSUE TITLE
Add test cases for the Input's page.

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#183]
## 📄 Context

Add e2e tests for the inputs page.

## 📈 Subtasks

- [x] Add test for header
- [x] Add test for search
- [x] Add test for Inputs table

## 🎯 Definition of Done

- [x] All new and existing e2e tests are passing
