### ISSUE TITLE
Add an "Application address" option to the "Send transaction" dialog

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-explorer#185]
## 📄 Context

Some applications need to know their address on the base layer to generate vouchers, such as NFT withdrawals.
To cover those use cases, we have the [`DAppAddressRelay`](https://github.com/cartesi/rollups-contracts/blob/v1.4.0/onchain/rollups/contracts/relays/IDAppAddressRelay.sol) contract on Rollups SDK v1.
By calling the `relayDAppAddress` function, and passing the application contract address as argument, the relay adds an input to the application's input box stating its address.
As of now, this relay is not supported by the Rollups Explorer.

Docs Ref: https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/relays/DAppAddressRelay/

## ✔️ Solution

Add an "Application address" option to the "Send transaction" dialog.
The only argument would be the application address.

## 📈 Subtasks

- [x] Add **Relay Address** Option in the selectable options.
- [x] Implement form logic to relay address
- [x] Add test cases.

## 🎯 Definition of Done

- [x] I can set and send the application address to be relayed to the off-chain machine.

## Extras

<details>
<summary><h3> Screenshot </h3></summary>

![Screenshot from 2024-05-24 11-19-06](https://github.com/cartesi/rollups-explorer/assets/9125226/19f6b626-7aa6-4d9c-a6b8-fefcfd64d8f5)

</details>

**Comment by guidanoli** [comment]
Just an observation: for Rollups SDK v2, the application contract address will be part of the input metadata, rendering the `DAppAddressRelay` useless. For that reason, we've removed it for v2.

**Comment by brunomenezes** [comment]
Hey @guidanoli, 
So you want access to use the [relay](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/relays/DAppAddressRelay/) is that it? Are you in need for Bugless?

**Comment by guidanoli** [comment]
Yes. As of Bugless v0.7.0 (which is being rebranded as Bug Buster) needs to know the application address in order to generate Ether withdrawal vouchers. Soon, however, we foresee this requirement to fall, as we allow bounties to be sponsored with ERC-20 tokens, and deprecate Ether. Also, for Rollups SDK v2, this relay will be removed, so it's something to consider. I don't know what is the current estimation for the v2 release, but I think this feature would benefit applications that need the application address. Namely, any application that allows the withdrawal of Ether, ERC-721 or ERC-1155 tokens.

**Comment by brunomenezes** [comment]
> Yes. As of Bugless v0.7.0 (which is being rebranded as Bug Buster) needs to know the application address in order to generate Ether withdrawal vouchers. Soon, however, we foresee this requirement to fall, as we allow bounties to be sponsored with ERC-20 tokens, and deprecate Ether. Also, for Rollups SDK v2, this relay will be removed, so it's something to consider. I don't know what is the current estimation for the v2 release, but I think this feature would benefit applications that need the application address. Namely, any application that allows the withdrawal of Ether, ERC-721 or ERC-1155 tokens.

Got it. Related to becoming deprecated later with rollups v2 that is not a problem as we will need to address other necessary changes anyway when adding support to v2.
