### ISSUE TITLE
Add input completion status

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-explorer#186]
## 📄 Context

When an input is sent to an application, it may be in one of the several possible [statuses](https://github.com/cartesi/grpc-interfaces/blob/v0.16.0/server-manager.proto#L177).
This information is already made available through the GraphQL interface, and can help developers debug their application and users have more feedback from their input.

Available Status Ref: https://github.com/cartesi/grpc-interfaces/blob/v0.16.0/server-manager.proto#L177.

## ✔️ Solution

Add the input status in the UI as a column in the table. **This would, of course, depend on a connection to a GraphQL endpoint.**

1. Add a new Column called `Status` with a interrogation sign to include a tooltip.
2. The tooltip wording is `Check the status by adding a connection. Click the ? in the row to add a connection.`
3. A row for an application without a connection should display `?` as a clickable call-to-action
 3.1. A click on it should open the `Connection creation modal`, with application address already filled.
 3.2 A mouse over it should display a tooltip with wording "Click to add a connection and inspect the input status."
4. For an application with a connection it should display the `status` informed by the app's graphQL in a `<Badge />` component just like the `Method` column.
5. Make sure the input status displayed is per index. e.g. index 1 may be `ACCEPTED` but index 2 a `REJECTED`.

## 📈 Subtasks

- [x] Add new input table header `Status` with tooltip (wording above).
- [x] Add call-to-action with hover tootip for non-connected Apps (wording above).
- [x] Add logic to handle call-to-action as stated above.
- [x] Add logic to automatic display the status of input (per input index) for connected Apps.
- [ ] Add test cases

## 🎯 Definition of Done

- [x] I can see the input's status for connected apps. 
- [x] I can hover or click the tooltip and read the intent of the new column and how to use it. 
- [x] I can click the `?` badge and start the `connection creation workflow` for that specific Application.
- [x] I can automatic see the input status for connected applications.

## Extras

<details>
<summary><h3>Screenshot</h3></summary>

![image](https://github.com/cartesi/rollups-explorer/assets/9125226/5fa062d4-a350-4204-80f7-d2b18e501a8a)
</details>

**Comment by brunomenezes** [comment]
Hi @guidanoli, I see the value here. I think a column `Status` will serve better than a `tab` since that is the "state" of the content displayed by the tab (if that makes sense). Let me refine a bit here and let me know your thoughts on that. 


1. Add a new Column called `Status` with a interrogation sign to include a tooltip.
2. The tooltip wording is `Check the status by adding a connection. Click the ? in the row to add a connection.`
3. A row for an application without a connection should display `?` as a clickable call-to-action
 3.1. A click on it should open the `Connection creation modal`, with application address already filled.
 3.2 A mouse over it should display a tooltip with wording "Click to add a connection and inspect the input status."
4. For an application with a connection it should display the `status` informed by the app's graphQL in a `<Badge />` component just like the `Method` column.
5. Make sure the input status displayed is per index. e.g. index 1 may be `ACCEPTED` but index 2 a `REJECTED`.

**Comment by guidanoli** [comment]
Great breakdown, @brunomenezes! I totally agree with this plan! Thank you very much. :grin:

**Comment by brunomenezes** [comment]
> Great breakdown, @brunomenezes! I totally agree with this plan! Thank you very much. 😁

Cool! I will update the issue description for development purposes.
