### ISSUE TITLE
Add test cases for the Connections page.

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#188]
## 📄 Context

Add e2e tests for the connections page.

## 📈 Subtasks

- [x] Add test for header
- [x] Add test for list
- [x] Add test for adding connection
- [x] Add test for removing connection

## 🎯 Definition of Done

- [x] All new and existing e2e tests are passing
