### ISSUE TITLE
Add test cases for the Application's summary page.

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#189]
## 📄 Context

Add e2e tests for the application's summary page.

## 📈 Subtasks

- [x] Add tests for header
- [x] Add tests for summary cards
- [x] Add tests for the latest inputs table

## 🎯 Definition of Done

- [x] All new and existing e2e tests are passing
