### ISSUE TITLE
Add test cases for the Application's input page.

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#190]
## 📄 Context

Add e2e tests for the application's inputs page.

## 📈 Subtasks

- [ ] Add test for header
- [ ] Add test for table
- [ ] Add tests for the inputs table
- [ ] Add tests for the search

## 🎯 Definition of Done

- [ ] All new and existing e2e tests are passing
