### ISSUE TITLE
Add Support to send Generic Input (Send Raw Input)

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#207]
## 📄 Context
Today, we can send a transaction to the add-input that expects a Hex format. But from the user perspective, it is not very friendly since the user needs to have this `hex` input ahead of time, and the form does not help with that. E.g. We could like the `cartesi-cli` send method to parse a valid JSON object i.e. `{"name": "James", "action":"create-game"}`. We can add this capability to the existing form.

## ✔️ Solution
Add support to parse `String encoding` that would convert a `UTF-8` string to Hex format. We will continue to support the field in entering the Hex format but also add a new way to facilitate the encoding of the `string`.

## 📈 Subtasks

- [x] Implement the Segment-Control for encoding options (Hex / String to Hex).
- [x] implement the new input to add the UTF-8 string. 
- [x] implement a result area of the encoded value when using the new String to hex format.
- [x] Add tests (if needed)

## 🎯 Definition of Done

- [x] I can add my string value and see the correct Hex result in the form.
- [x] The hex sent to my rollups application is correctly encoded in Hex format.
