### ISSUE TITLE
Send raw input

### ISSUE THREAD

**Issue by tuler** [cartesi/rollups-explorer#21]
## 📄 Context

Inputs can be sent to any application by interacting with the [InputBox](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/sol-input/#addinput) smart contract.
The payload of the input is a raw byte array.

## ✔️ Solution

Create a form to send raw inputs to an application through the InputBox.
We can use a simple [Textarea](https://v7.mantine.dev/core/textarea) when the user inputs a bytes payload as an hex string.

Autocomplete for the application address can be implemented as an improvement, similar to what is proposed at https://github.com/cartesi/rollups-explorer/issues/19

## 📈 Subtasks

- [x] implement the UI
- [x] implement the transaction

## 🎯 Definition of Done

- [x] input payload sent successfully
