### ISSUE TITLE
Update mantine packages

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#220]
## 📄 Context

[Mantine](https://www.npmjs.com/package/@mantine/core) has upgraded their library a few minor versions above what we current install in the app. We have `7.7.1` and the latest version is `7.11.2` so lets upgrade to the latest version. 

As a prerequisite check their [release logs](https://github.com/mantinedev/mantine/releases) for any potential breaking changes and also check their [repo](https://github.com/mantinedev/mantine/issues) for any raised issues related to the new version.

Make sure to throughly test the UI for any regressions in the mantine components that we use. Specifically, pay attention to the transaction forms.

## 📈 Subtasks

- [x] Check Mantine release log and github issues
- [x] Upgrade Mantine libraries to latest version 
- [x] Test the app for regressions paying special attention to the transaction forms
- [x] Fix any potential issues related to breaking changes in the new version
