### ISSUE TITLE
Upgrade NextJS to latest version

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#221]
## 📄 Context

[NextJS](https://www.npmjs.com/package/next?activeTab=readme) has upgraded their framework one minor version above what we current install in the app. We have `14.1.4` and the latest version is `14.2.5` so lets upgrade to the latest version. 

As a prerequisite check their [release logs](https://github.com/vercel/next.js/releases/tag/v14.2.0) for any potential breaking changes and also check their [repo](https://github.com/vercel/next.js) for any raised issues related to the new version.

Make sure to throughly test the UI for any regressions. Specifically, pay attention to the transaction forms.

## 📈 Subtasks

- [x] Check NextJS release log and github issues
- [x] Upgrade NextJS libraries to latest version 
- [x] Test the app for regressions paying special attention to the transaction forms
- [x] Fix any potential issues related to breaking changes in the new version
