### ISSUE TITLE
Upgrade ReactJS to latest version

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#225]
## 📄 Context

[ReactJS](https://www.npmjs.com/package/react) has upgraded their framework one minor version above what we current install in the app. We have `18.2.0` and the latest version is `18.3.1` so lets upgrade to the latest version. 

As a prerequisite check their [release logs](https://github.com/facebook/react/releases/tag/v18.3.1) for any potential breaking changes and also check their [repo](https://github.com/facebook/react) for any raised issues related to the new version.

Make sure to throughly test the UI for any regressions. Specifically, pay attention to the transaction forms.

## 📈 Subtasks

- [ ] Check ReactJS release log and github issues
- [ ] Upgrade ReactJS to latest version 
- [ ] Test the app for regressions paying special attention to the transaction forms
- [ ] Fix any potential issues related to breaking changes in the new version
