### ISSUE TITLE
Upgrade react-testing library

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#227]
## 📄 Context

[React testing library](https://www.npmjs.com/package/@testing-library/react) has upgraded their framework one major versions above what we current install in the app. We have `14.0.0` and the latest version is `16.0.0` so lets upgrade to the latest version. 

As a prerequisite check their [release logs](https://github.com/testing-library/react-testing-library/releases/tag/v16.0.0) for any potential breaking changes and also check their [repo](https://github.com/testing-library/react-testing-library) for any raised issues related to the new version.

Make sure to throughly test the UI for any regressions. Specifically, pay attention to the transaction forms.

## 📈 Subtasks

- [x] Check React testing library release log and github issues
- [x] Upgrade the library to latest version 
- [x] Ensure all existing unit tests work as before and pass ok
