### ISSUE TITLE
Add Export and Import for Specifications

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#229]
## 📄 Context
We have a new Specification feature to help decode abi-encoded data on the input's payload. The created specs persist on local storage and belong to the domain where you run the web application (e.g., localhost). So, to avoid the tedious task of recreating them every time you run the App in a different domain, an import/export feature will be helpful.

## ✔️ Solution
Create a **versioned** importer/exporter. The exporter should generate a JSON file with specific properties (described below). The importer should be able to accept only JSON extensions and work on the designated version. 

* The **export** action should be visible when at least one specification is created. 
* Exported file name to be `cartesiscan_specifications.json`
* All specifications should be exported. Filtering does not affect the exported result (i.e. filter by JSON ABI / ABI Params). 
* The **import** action should be available when no specifications are created (adjust the existing messages to accommodate the import). It should also be available when there are one or more specifications.
* Handle all possible points of error when reading the imported file and notify the user as such. e.g., the exported version does not match, meaning the file was tampered with.
* Limit the possible file extensions to be imported to only `.json`; 

## Example of Data Format

```ts
interface SpecificationExport {
 name: 'cartesiscan_specifications_export';
 version: number;
 timestamp: number;
 specifications: Specification[]
}
```

### References: 
**Web APIs**: URL , Blob, File.

## 📈 Subtasks

- [x] Implement Exporter Logic and UI
- [x] Implement Importer Logic and UI
- [x] Handle and notify Errors .
- [x] Add tests. 

## 🎯 Definition of Done

- [x] I can successfully export my existing specifications.
- [x] I can import and use my specifications. 
- [x] I can see any errors related to the file I am trying to import.
