### ISSUE TITLE
Update vitest libraries

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#234]
## 📄 Context

[Vitest](https://www.npmjs.com/package/vitest) has upgraded their framework two major versions above what we current install in the app. We have `0.34.2` and the latest version is `2.5.0` so lets upgrade to the latest version. 

As a prerequisite check their [release logs](https://github.com/vitest-dev/vitest/releases) for any potential breaking changes and also check their [repo](https://github.com/vitest-dev/vitest) for any raised issues related to the new version.

## 📈 Subtasks

- [x] Check Vitest library release log and github issues
- [x] Upgrade the library to latest version 
- [x] Ensure all existing unit tests work as before and pass ok
