### ISSUE TITLE
Add ABI encoding capability to `send raw input`

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#251]
## 📄 Context
Currently, when sending a transaction, the `Raw input` form provides two ways of filling the data to be sent: `Raw`, i.e., as a Hex value, or `String to Hex`, where the user sets a string value, and the application will convert it to Hex. An interesting third way is for the user to define or choose an ABI, decide the function method and set the argument(s) value(s) if any is required. The application would take care of the ABI encoding the data. 

**Also, it is an excellent moment to rebrand that form name from `Raw Input` to `Generic Input`.**

## ✔️ Solution

Change the form name to reflect its capabilities and add the ABI encoding feature with the following requirements:

* Rebrand the `Raw Input` form to `Generic Input` form
* The user should be able to select an existing Specification (JSON_ABI type only)
* The user should be able to define an ABI on the fly (human-readable format or JSON ABI format)
* Once the ABI is available to the form (filled or selected):
    * A `combobox` with all the ABI items where the type is `function` should be listed (i.e. no event, constructor, etc, to be included).
    * The text content should be the function signature, e.g. `ownerOf(uint256)`.
* Once a function is selected and it has arguments; 
    *  Dynamic inputs should become available following the ABI item inputs order, with the name as the input's label (fallback to the ABI item input type in case the name is missing, e.g. address, uint, string). 
    * The order of these dynamic inputs must be respected so the transaction is prepared correctly. 
* If a selected function has no arguments;
    * Display a simple centralised info level message using copy “No input arguments defined for {#function signature}.”
* The send should be enabled once all required fields are filled out and no errors are captured.

**PS: Check [Viem docs](https://viem.sh/docs/getting-started) to support conversions here and there e.g. function signatures**

## 📈 Subtasks

- [x] Rename the form name from `Raw Input`.
- [x] Implement the new ABI encoding logic.
- [x] Handle errors.
- [x] Add tests.

## 🎯 Definition of Done

- [x] I can ABI encode my data and send a transaction to my Cartesi Application.
- [x] I can receive the ABI encoded data on my Cartesi Application and decode it correctly using the same ABI. 
- [x] CI checks are passing.
- [x] Vercel deployments are live with success.
