### ISSUE TITLE
Add capability to a byte-slice to be optional

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#252]
## 📄 Context
We encounter a few challenges when dealing with ABI non-standard encoded data(i.e., encodePacked function) using the specifications. As we're Dogfooding the specifications feat to use with Cartesi's Portals and Relay contracts that use non-standard encoding, we encounter a few situations where the `execLayerData` is unavailable, and exceptions would be raised. That is possible to happen with encoded data for two portals [EtherPortal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/EtherPortal/) and [ERC20Portal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC20Portal/) because the `execLayerData` is passed directly to the `encodePacked` function call, and such value as e.g. `0x` is ignored in the output generated. 

**PS: That does not happen for the other portals, i.e. ERC721, ERC1155Single and ERC1155Batch. Because the encoding used for this data (i.e. baseLayerData and execLayerData) is the standard ABI encoding first, then passed down to the `encodePacked()` call.** If curious, here is the [code reference](https://github.com/cartesi/rollups-contracts/blob/main/contracts/common/InputEncoding.sol#L14)

**PS²: This change will be used first with our System specs. Later, it will be available for UI use.**

## ✔️ Solution

Add a new optional property to the `SliceInstruction` type to signal to the **decoder** not to throw the exception caused by slicing a defined byte range that is out-of-bound and rather gracefully continue and set a `nil` value to that defined instruction. 

* Add a new optional property to the `SliceInstruction` type. `boolean` is a good candidate.
* Handle the possible exception caused by the `slice()` call for the `SliceInstruction` instance when that property is `on` and set a nil value for the output value for the instruction when building the decoded value
* The decoder should throw the exception as it would today when this option is `off`(i.e. when the `slice()` throws the exception).
* Update the System Specification for EtherPortal to retrieve the last bytes as `execLayerData`.
* Update the System Specification for ERC20Portal to retrieve the last bytes as `execLayerData`.

## 📈 Subtasks

- [x] implement changes to the Specification types affected. 
- [x] implement changes to the decoder logic.
- [x] Update system specifications [`EtherPortal`, `ERC20Portal`]
- [x] Add tests.

## 🎯 Definition of Done

- [x] I can see the `execLayerData` decoded property with a `nil` when its value is not available in the payload (For EtherPortal)
- [x] I can see the `execLayerData` decoded property with a `nil` when its value is not available in the payload (For Erc20Portal)
- [x] Otherwise, I see the value defined in the payload. 
- [x] CI is passing the checks.
