### ISSUE TITLE
Add a new Decoded content segment for `input details`

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#253]
## 📄 Context
Currently, we are reusing the `Raw` content segment in the `Input` tab to display the decoded value when a specification can decode the payload. A new conditional segment for the decoded content is necessary so the raw content (i.e. Hex value) is still available for any other use required by the user. 

## ✔️ Solution

Add a new `Decoded` content segment to the `InputDetails` component in the `packages/ui`. That segment should only be used when we have a decoded payload; otherwise, it should be disabled.

* This new Decoded content segment should be turned off by default.
* A new API is necessary to turn this content type section on/off. **Keep it open for the possibility of upcoming segments that would also be configurable.**
* Only the new `Decoded` segment should be an option to be flicked `on` / `off`. The others—i.e., `Raw`, `As Text`, and `As JSON` should not be in the options for modification but stay as they are.
* In the apps/web, adjust the client component to use the new API and correctly set the input's content based on the `content-type` set. _For reference, have a look at #246 as it is already dealing with that `content-type` dynamics, e.g. the `Raw` content for the voucher tab is only the Hex value, not a decoded content_ 

Here's a case for the last bullet point: If the user is in the decoded section for a Portal input and decides to change to the `Raw` section, the content should be switched to the Hex value. It's that simple. 

## 📈 Subtasks

- [x] Implement the changes to add a new Decoded section.
- [x] Expose a new API to change the state of configurable content sections. 
- [x] Implement the changes in the web app input details to leverage the new Decoded content section and API. 
- [ ] Add tests 

## 🎯 Definition of Done

- [x] I can see and access the decoded payload in the designated new content segment. e.g. checking a Portal input
- [x] I can't access the decoded content segment without a decoded payload. It should be disabled. 
- [ ] CI checkings are passing.
- [ ] Vercel deployments are successful.

**Comment by brunomenezes** [comment]
I suggest picking only that issue once #246 is merged. Files changed will cause conflicts.
