### ISSUE TITLE
Expose UI for setting the "optional" flag of a byte-slice for ABI Parameter specifications

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#264]
## 📄 Context

This task is a continuation of https://github.com/cartesi/rollups-explorer/issues/252.

Extend the ABI Parameter specification form and more specifically the **Add decoding steps by byte range** option, by adding a checkbox for toggling the `optional` flag of a byte-slice. 

This will allow users to control the decoding behaviour for that byte-slice:
 - if the slice throws a `SliceOffsetOutOfBoundsError` and the `optional` flag is turned on, a fallback value of `nil` is used, so no errors will be raised.
 - otherwise, if a `SliceOffsetOutOfBoundsError` error is raised and the `optional` flag is turned off, decoding will fail with raised errors.

Suggested UI:
![optional-checkbox](https://github.com/user-attachments/assets/462275e5-f79c-47c8-b6dc-bcf24d129acc)

## 📈 Subtasks

- [x] Add checkbox that toggles the `optional` flag for the byte-slice
- [x] Add tooltip explaining the purpose of the `optional` flag next to the checkbox
- [x] Add tests for the changes

## 🎯 Definition of Done

- [x] I can set the `optional` flag for a byte-slice in my ABI Parameter specification.
- [x] Input with the same ABI Parameter specification is:
  - decoded without raised errors when the byte slice is optional and missing
  - not decoded and errors are raised when the byte slice is not optional and missing
- [x] All tests are passing

**Comment by nevendyulgerov** [comment]
Hi, @brunomenezes , can you please review the description in case I've missed some details?

**Comment by brunomenezes** [comment]
> Hi, @brunomenezes , can you please review the description in case I've missed some details?

Hi @nevendyulgerov, I think that is the gist of that (default is off). A couple of comments: **First**, perhaps as it is a `switch`, having it inline with the label would feel more aligned with the other switches on the page, and the **second** is to display that information in the `Review your definition` section that appears after adding the first slice _(not sure if you're considering it and just forgot to include here)_
