### ISSUE TITLE
ERC-20 - Fix unnecessary network calls and UI loading-states.

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#279]
## 📄 Context

When using the send transaction feature in the ERC-20 form, when switching between the rollups version, the deposit button displays its loading state when the amount is zero.

PS: That is just a cosmetic improvement as you actually can't proceed with the deposit as 0 is an **invalid amount**

## ✔️ Solution
Given the parameters, a `prepare` statement goes into the network to check if the current transaction will be successful. The assumption is that the problem lies there; having a non-nil-undefined at the moment may be enough to enable that query. So the goal is to fix that condition and only allow that for amounts larger than 0( e.g. 0.1, 0.001,etc)

## 📈 Subtasks

- [x] Investigate and apply the fix to avoid unnecessary network calls. 
- [x] Add test cases. 

## 🎯 Definition of Done

- [x] Invalid amounts will not trigger perceived network calls in the UI (i.e. Deposit loading state displaying)
- [x] CI tests are passing.
- [x] Vercel builds are passing.
