### ISSUE TITLE
Ether deposit - Improve error message checks

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#280]
## 📄 Context

When using the deposits through the Ether portal, the validation for the amount exceeding the balance takes a long time as it is waiting for a `prepare` call to resume. Instead, retrieving the balance information from the wallet connected and adding this new validation as the user fills the form would be faster and more efficient.

## ✔️ Solution
Get the current ETH balance of the connected account and include it in the validation for the amount the user defines rather than wait for the return of the `prepare` checks.

wording: `The amount ${amount} exceeds your current balance of ${balance} ETH`

## 📈 Subtasks

- [x] Add the new validation for faster local validation in terms of an amount exceeding the balance.
- [x] Add test cases.

## 🎯 Definition of Done

- [x] As I try to add an amount bigger than my balance, I can quickly see the error message.
- [x] An invalid form will not allow the user to proceed with the deposit.
- [x] CI checks are passing.
- [x] Vercel preview builds are passing.
