### ISSUE TITLE
Improve ERC20Portal data display

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#39]
## 📄 Context
We have knowledge and control over how to parse the encoded content of an **ERC20Portal deposit**. Therefore, an improvement can be made to display the content of this encoded payload in the sections `As Text` and `As JSON`. 

## ✔️ Solution
A code reference to the solidity code that does the encoding: [InputEncoding.sol#encodeERC20Deposit](https://github.com/cartesi/rollups-contracts/blob/73cee6a4b8b7d6874601dd2c6fa930e0dba39964/onchain/rollups/contracts/common/InputEncoding.sol#L40)
ERC20Portal ABI reference for the function: [depositERC20Tokens](https://github.com/cartesi/rollups-contracts/blob/main/onchain/rollups/deployments/sepolia/ERC20Portal.json#L15)
Leverage the Ethereum utility library [viem](https://viem.sh/docs/getting-started.html) that is available in the project.

The decoded version could become an object with the same name fields and easily be consumed by the sections mentioned as JSON. 

_PS: Because it is `encodePacked` the decoding needs to be done manually; it is not just drop the ABI. But it is still worth noting the field names in the refs above._

## 📈 Subtasks

- [ ] Decode the ERC20Portal input payload
- [ ] Display the decoded content `As Text`
- [ ] Display the decoded content `As JSON`

## 🎯 Definition of Done

- [ ] The ERC20Portal payload content is now human-readable.

## 📸 Snapshots (extra)

Input row level content
<img width="1451" alt="Screenshot 2023-10-21 at 12 25 12" src="https://github.com/cartesi/rollups-explorer/assets/1239768/780c136f-a729-452d-b04e-c823d4451df8">

Data sections
<img width="1464" alt="Screenshot 2023-10-21 at 12 25 22" src="https://github.com/cartesi/rollups-explorer/assets/1239768/c4e2abd1-3db7-4581-87d8-53207cee7d0b">

**Comment by brunomenezes** [comment]
I saw the PR was closed and I will also close this issue.

cc: @dandheedge

**Comment by brunomenezes** [comment]
I saw the PR was closed and I will also close this issue.

cc: @dandheedge
