### ISSUE TITLE
DApp connection

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#4]
## 📄 Context
The application lists all the inputs going into different DApps. The displayed payload belongs to the Input sent, but we can't see the possible outputs related to said input. Hence, the user should be able to connect to the DApp to check possible outputs, that belong to the Input inspected.

## ✔️ Solution
Provide a feature to connect to the DApp that the inspected input belongs to and a UI to display the paginated content of possible outputs, i.e. Voucher / Reports / Notices. 

Requirements:
* User must provide the URL to the DApp graphQL backend (No guessing from the application part)
* For that initial version, the configuration will be persisted on the user's browser to avoid tedious repetition.
* When a configuration exists, it should not be eagerly activated when the user returns but by deliberate click to connect to avoid (multiple calls against the DApp's backend).
* For this version, decoding continues to be the current offered one i.e. RAW / as Text / As JSON

## 📈 Subtasks

- [x] Add DApp connection flow: 
  - [x] Dialog to add a graphQL URL to connect to the DApp backend
  - [x] An action to test the connection.
  - [x] Display feedback on success or failure to establish the connection.
  - [x] Configuration is persistent through page refresh and or browser closures. 
  - [x] When no connection is configured for the DApp, display a button to start the connection creation.
  - [x] All input rows belonging to the same DApp benefit from the existing connection.
  - [x] Add test cases
- [x] Update the existing `data` (Input Details feature):
  - [x] Update the data box to accommodate new tabs inputs/vouchers/reports/notices.
  - [x] Update the data box content area to have the encoding as grouped actions (raw / text / JSON).
  - [x] Give feedback when one of the Tabs has no content to display. e.g. Dimmed tab, content area updated with copy
  - [x] The Outputs content should be paginated, showing only one at a time.
  - [x] Add the capability to signal and trigger the connection to load content.
  - [x] Add the capability to display a loading state inside the content when dealing with paginated content.  
  - [x] Add test cases.
  - [x] Add stories for the new UI components.

## 🎯 Definition of Done

- [x] The viewer can configure the graphQL URL and save it persistently.
- [x] The viewer can navigate through existing outputs for the input row they inspect.
