### ISSUE TITLE
Problem with current bundler setup

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#48]
## 📄 Context
While developing #4, I stumbled upon a blocker to write tests to the `InputDetailsView` component that uses components from `@cartesi/rollups-explorer-ui`. That may cause a similar issue when writing tests for other components also using the package. Just changing the bundling to ESM by the configuration causes odd problems between rainbow-kit with **NextJS13** server rendering and hydration (but only in dev mode 🫠 so confidence with that framework is super high 👍 )

<details>
<summary><h3>Logs</h3></summary>

```
 FAIL  test/components/inputDetailsView.test.tsx [ test/components/inputDetailsView.test.tsx ]
Error: require() of ES Module /rollups-explorer/packages/rollups-wagmi/dist/index.js from /rollups-explorer/packages/ui/dist/index.js not supported.
Instead change the require of /rollups-explorer/packages/rollups-wagmi/dist/index.js in /rollups-explorer/packages/ui/dist/index.js to a dynamic import() which is available in all CommonJS modules.
 ❯ async /rollups-explorer/apps/web/src/components/inputDetailsView.tsx:2:31
 ❯ async /rollups-explorer/apps/web/test/components/inputDetailsView.test.tsx:4:39
```
</details>

## ✔️ Solution

Change how we are bundling the packages, moving to `ESM` only and making the module the main entry instead of the `commonJS` one. Also, address the quirks of NextJS13.

**PS: in theory, rainbow-kit has nothing to do with our ui package**

## 📈 Subtasks

- [x] Change the bundling to ESM
- [x] Write tests for a component using the UI package, e.g. `InputDetailsView`.
- [x] Investigate the NextJS 13 problem with RainbowKit

## 🎯 Definition of Done

- [x] Able to write tests for components importing from `@cartesi/rollups-explorer-ui.`

**Comment by brunomenezes** [comment]
Manually closing since it was a PR merged into a branch that is not `main`
