### ISSUE TITLE
Cartesi Logo as clickable link

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#58]
## 📄 Context
At the moment, the Cartesi logo is just an "image". It is pretty standard that when clicking the logo of a web app/page, you would return to the home `/`, which is so common that it got to us as feedback to add that. 

**Header reference:**
![image](https://github.com/cartesi/rollups-explorer/assets/1239768/42f00a20-2902-408a-b400-c0dff7889d5a)

## ✔️ Solution
Make the cartesi logo a clickable link. When clicking the logo the user should be redirected to the home `/`. 

* Functional: Use the `next/link`. So, the routing experience is smooth and not a complete refresh.
* Design: Check mantine.dev documentation to correctly integrate **NextJS 13** Link and the UI component.
* Design²: Keep the current logo size and colour.

## 📈 Subtasks

- [x] Move over the logo displays the address it is going like any Anchor `<a>`
- [x] Click on the Cartesi Logo displays the home page `/`.

## 🎯 Definition of Done

- [x] Click on the Cartesi logo redirects to `/.
