### ISSUE TITLE
Add Footer with relevant information

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#59]
## 📄 Context
We must include a footer with relevant information about the application and links to the socials and Cartesi information. 

## ✔️ Solution
As a good start, we need a footer divided into columns: one for the Application's information/copyright `©` and the second column divided into sections of valuable links. Below, I am adding a screenshot of a `hack` of what it would look like, including the icons from the `Tb` family, logo and copy. _**On small screens**, it should be one column; the copyright is the last content displayed._

For the first column content, you can use the copy described in the screenshot; the logo is available in the Application.

<img width="1470" alt="footer-content-2" src="https://github.com/cartesi/rollups-explorer/assets/1239768/fab58f12-4d2f-4947-a8dc-4c076b06f868">

### Copyright links
| Copy | Link To | 
| :---: | :---: |
| See AUTHORS | https://github.com/cartesi/rollups-explorer/blob/main/AUTHORS |
| See LICENSE | https://github.com/cartesi/rollups-explorer/blob/main/LICENSE |

### For CartesiScan section in order of appearance
| Icon | Copy | Link To | 
| :---: | :---: | :---: |
| `TbBug` | Report a bug | [Copy this link](https://github.com/cartesi/rollups-explorer/issues/new?assignees=&labels=Type%3A+Bug%2CStatus%3A+Needs+triage&projects=&template=2-bug.md&title=) |
| `TbMessage2Code` | Feature request | [Copy this link](https://github.com/cartesi/rollups-explorer/issues/new?assignees=&labels=Type%3A+Feature%2CStatus%3A+Needs+triage&projects=&template=1-feature.md&title= ) |
| `TbBrandGithub ` | Contribute | [Copy this link](https://github.com/cartesi/rollups-explorer/blob/main/CONTRIBUTING.md) |
| `TbBrandDiscord` | Discord |  https://discord.gg/pfXMwXDDfW | 

### For the General section in order of appearance

| Copy | Link To | 
| :---: | :---: |
| Docs |  https://docs.cartesi.io/ |

**PS: A suggestion is not to use the `AppShell.Footer` because it is `position fixed`, which would pass the impression that the App content is inside an `<Iframe />`.** 

## 📈 Subtasks

- [x] Info about the Application is set.
- [x] Application copyright is included, and links navigate to the correct sources.
- [x] CartesiScan section is set, and links navigate the user to the correct places.
- [x] General section is set, and links navigate the user to the correct place.
- [x] Links open in a new tab instead of the same.
- [x] Dark/light mode is taken into consideration and UI looks ok on both modes.
- [x] On small screens, the footer content is displayed as one column, and the copyright is the last content displayed.
- [x] Add unit tests

## 🎯 Definition of Done

- [x] Footer content is in place.
- [x] Links navigate to the correct targets.
- [x] Is coherently aligned on big and small screens.

**Comment by brunomenezes** [comment]
I am assigning myself while that is blocked. 

@tuler, Could you check if you agree with the copy I added in the screenshot? That aligns with what we were discussing, but I want to double-check.

**Comment by tuler** [comment]
The copyright line is not that anymore.
I’d remove the about us and twitter link.

**Comment by brunomenezes** [comment]
> The copyright line is not that anymore. I’d remove the about us and twitter link.

Oh yeah! I forgot about the copyright line change. I made the adjustment (screenshot updated)
