### ISSUE TITLE
Rearrange navigational links

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#62]
## 📄 Context
The header is becoming crowded with navigation and call-to-action kind of elements. Let's make the navigation part in a separate application area based on screen sizes, i.e. a Navbar.

## ✔️ Solution
By moving page links from the header to the existing Navbar. Also, updating the current Navbar behaviour; 

* Adjust the Navbar to maintain the current behaviour/content for small screens, but it becomes always visible for big screens.
* Remove the links [`Home`, `Applications`] from the header to the Navbar. 
* You may need to adjust the default width for the desktop in case the area feels too big for the content. _(check the theme object for that)_
* Header should keep the `Connect Wallet`, `Deposits`, `dark/light mode` and `dots` buttons on a big screen.
* The burger icon continues to only show up on small screens.
* The Navbar should be collapsed by default on small screens.

## 📈 Subtasks

- [x] Navbar is always visible on **big screens.**
- [x] Navbar is collapsed by default on **small screens.**
- [x] Navbar displays the current connect / deposit actions on **small screens.**
- [x] The links were moved from the header to the NavBar on **big screens.**

## 🎯 Definition of Done

- [x] The wallet-related actions and navigational links are visible on small screens.
- [x] The Navbar only displays the navigational links on big screens.

**Comment by brunomenezes** [comment]
There is PR that may affect the changes here. So keep a eye on https://github.com/cartesi/rollups-explorer/pull/61
