### ISSUE TITLE
Add Connection shortcuts on Applications page

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#63]
## 📄 Context

The `Connection` is a feature added to support inspecting notices/vouchers/reports of a specific DApp. Currently, we can create a connection by clicking the `three dots` in the top-right corner of the page (The user needs to fill in the app address + the graphQL URL) and also through the data area when inspecting the `Input` tab for example; the user will see a `Connect` button in case a connection is not available for that DApp (Same form opens but the address is already filled). We want to provide the same experience on the Applications page.  

## ✔️ Solution
On the applications page, let's update the content of the applications table.

* Shorten all the addresses (application/owner) to make room.
* Add a new column (Head title `URL`) beside the `Owner` displaying the URL address in case it exists; otherwise, show `N/A`.
* When a connection is unavailable, an `add connection` ActionIcon should be visible beside the `Inputs` ActionIcon.
* When a connection is available, a `Disconnect` ActionIcon should be visible beside the `Inputs` ActionIcon.
* More details on the action button:
  * It should only display one or the other.
  * The `Add connection` should use the icon`TbPlugConnected` and start the existing creation modal form. When hovering, a tooltip should display `Add a connection.`.
  * The `Disconnect` should use the icon `TbPlugConnectedX` and remove the connection. When hovering, A tooltip should display `Remove connection.`
* When the creation modal opens for an application, the Application address should already be filled.

**PS: The connection feature has hooks with all possible actions to be used and covers all the needs here. Have a check.**

## 📈 Subtasks

- [x] All Addresses but the URL in the table row are shortened.
- [x] A third column displays the URL for the App in the row
- [x] An add connection `<ActionIcon />` is visible for Applications without a connection.
- [x] A disconnect `<ActionIcon />` is visible for connected Applications.
- [x] When clicking the add-connection for an App, display the form with the address filled.
- [x] Add test cases.

## 🎯 Definition of Done

- [x] A connection can be created for a specific Application.
- [x] A connection can be easily removed from an Application.
- [x] The Address for the application and owner are shortened. 
- [x] The GraphQL URL is visible as a third column when a connection is available.
