### ISSUE TITLE
Add ERC-721 Deposit Support

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#72]
## 📄 Context

DApps accept deposits of ERC-721 tokens by interacting with the [ERC721Portal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC721Portal/) smart contract.

Before the transfer, the caller should change the token's approved Address to the **Portal Address**.

## ✔️ Solution

Documentation about the ERC721Portal transfer:
https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC721Portal/

EIP-721: https://eips.ethereum.org/EIPS/eip-721
EIP-165: https://eips.ethereum.org/EIPS/eip-165

### Overall Form Structure
* The input for the application should use the autocomplete by fetching the Apps list from the API. 
* The input for ERC-721 contract. _ps: Autocomplete will come in the future (new feature in the API required)_
* The input for the token-id. **(A bit more details below)**
* There are two new fields for the `Advanced` area, unlike the ERC-20, which has one.
  * One for the Base layer.
  * One for the execution layer.

For the token-id input
* Below the input, display the balance (e.g. `balance: 2 BAYC` for Bored ape); if the symbol name is not available, only display the numeric part.
* When the **enumerable extension** `tokenOfOwnerByIndex` is not available
  * The input should be `text` type for the user to manually enter the token-id.  
* When the **enumerable extension** `tokenOfOwnerByIndex` is available
  * If the user owns 1+ tokens, the input should be a `select` listing all token IDs owned.   
  * If the user owns nothing, just fallback to the `text` type described above.

### Extra
Some mainnet ERC-721 contracts to help. 

Bored Ape Yacht Club: 0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D
CryptoKitties: 0x06012c8cf97BEaD5deAe237070F9587f8E7A266d (Older does not have enumerable extension)
  
## 📈 Subtasks

- [x] Create the form to deposit ERC-721 tokens.
- [x] Implement the `approve` transaction.
- [x] Implement the `depositERC721Token` transaction
- [x] Add test cases

## 🎯 Definition of Done

- [x] The transaction can be completed with success.

**Comment by brunomenezes** [comment]
@tuler, is there anything I missed in the details of this issue? 

Also, I think that will spawn a new issue on the API to start looking into the ERC721Portal as the sender to index token meta [`name`, `token`, `tokenUri`] if that is useful. cc: @guidanoli

**Comment by guidanoli** [comment]
[EIP-721] also defines two OPTIONAL extensions for token contracts.
You can check if any given token contract implements an extension through [EIP-165].

- `ERC721Metadata`:
  - `name()(string)` — token name
  - `symbol()(string)` — token symbol
  - `tokenURI(uint256)(string)` — token URI from token ID
- `ERC721Enumerable`:
  - `totalSupply()(uint256)` — number of tokens $n$
  - `tokenByIndex(uint256)(uint256)` — token ID from index $\in [0,n)$
  - `tokenOfOwnerByIndex(address,uint256)(uint256)` — token ID from owner $\alpha$ and index $\in [0,m)$, where $m := balanceOf(\alpha)$

[EIP-721]: https://eips.ethereum.org/EIPS/eip-721
[EIP-165]: https://eips.ethereum.org/EIPS/eip-165

**Comment by guidanoli** [comment]
For enumerable ERC-721 tokens, you can:
- list all tokens, with `totalSupply` and `tokenByIndex`
- list all tokens owned by some address, with `balanceOf` and `tokenOfOwnerByIndex`

Either one could be used for auto-complete.

**Comment by brunomenezes** [comment]
@guidanoli, 
Humm, I think initially making use of the meta (name + symbol) to behave like the other forms that display the token symbol + the enumerable (balanceOf + tokenOfOwnerByIndex) to fill a `<Select />` to select the token-id the user wants to make the transfer is an excellent first version, what do you guys think? Settling for that I will just polish the issue for situations and messages to be displayed and remove the `Status` labels. 


cc: @tuler (Emojis also count 😄 )

**Comment by guidanoli** [comment]
@brunomenezes Just pointing out that I am not sure how widely used is the enumerable extension, so you might want to do some research to evaluate how critical would this feature be. :grin:

**Comment by brunomenezes** [comment]
I updated the description with more information and also extra information to help during development. Thanks, @guidanoli, for the insights and for pointing to the `CryptoKitties`. It does not have the extensions you mentioned, so it is an excellent material to use during dev.
