### ISSUE TITLE
Add loading and error states to pages

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#82]
## 📄 Context

The home and applications pages are missing loading and error states. Those states are useful for displaying a loading indicator while content is being loaded for them and for displaying a fallback UI when an error occurs and the page cannot be displayed. The error state also allows for resetting the page and attempting to load it again. Both states will provide overall a better UX.

## ✔️ Solution

Using the work done in https://github.com/cartesi/rollups-explorer/pull/81, we can leverage `PageLoader` and `PageError` components to easily display both states for each page.

## 📈 Subtasks

- [x] Add `loading.tsx` and `error.tsx` files for the home page
- [x] Add `loading.tsx` and `error.tsx` files for the applications page
- [x] Add `loading.tsx` and `error.tsx` files for the applications [address] page
- [x] Use for both pages components `PageLoader` and `PageError`

## 🎯 Definition of Done

- [x] Home page displays a spinner while content for it is being loaded.
- [x] Home page displays a fallback UI when an error occurs while trying to load content for it.
- [x] Applications page displays a spinner while content for it is being loaded.
- [x] Applications page displays a fallback UI when an error occurs while trying to load content for it.
- [x] Applications [address] page displays a spinner while content for it is being loaded.
- [x] Applications [address] page displays a fallback UI when an error occurs while trying to load content for it.
