### ISSUE TITLE
Remove deprecated configuration for GraphQL codegen

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#99]
## 📄 Context

As we are using a "meta-framework"  (i.e. NextJS 14) that also allows using RSC to run server-side code, the use of hooks is not possible. Therefore, as discussed [here](https://github.com/cartesi/rollups-explorer/pull/92#discussion_r1446763519), we added graphQL codegen instructions to create different files for different purposes. Now, it is time to remove the deprecated configuration and update the import path of the react hooks used in the client-side parts of the web app.

## ✔️ Solution
Remove the codegen config marked as deprecated and unused variables. Also, upgrade the import path of hooks.

PS: `yarn build` inside the `apps/web` directory helps catch import failure after removing the configuration.

## 📈 Subtasks

- [x] Remove deprecated codegen config
- [x] Update the react-hooks import path used. 

## 🎯 Definition of Done

- [x] The new graphql folder generated only contains the following folders: `explorer/` and `rollups/`. i.e. index.ts is gone.
- [x] Hooks continue to work and make correct calls after import updates.
- [x] Github CI are passing.
- [x] Vercel build is passing.
